### ISSUE TITLE
ld.lld: error: undefined symbol: __stack_chk_guard

### ISSUE THREAD

**Issue by vic-sys** [xperiaossdev/device_sony_pdx215#1]
I am trying to compile EvolutionX 7.7 on Ubuntu 18.04 
I am facing this error after make，

  AR      drivers/usb/typec/tcpm/built-in.a
  CC      drivers/usb/typec/bus.o
  AR      drivers/usb/typec/ucsi/built-in.a
  AR      drivers/usb/storage/built-in.a
  AR      drivers/usb/typec/built-in.a
  AR      drivers/usb/built-in.a
  AR      drivers/built-in.a
  GEN     .version
  CHK     include/generated/compile.h
  LTO     vmlinux.o
  MODPOST vmlinux.o
WARNING: "embms_tm_multicast_recv" [vmlinux] is a static EXPORT_SYMBOL
WARNING: "tsens_mtc_reset_history_counter" [vmlinux] is a static EXPORT_SYMBOL
  MODINFO modules.builtin.modinfo
  LD      .tmp_vmlinux.kallsyms1
ld.lld: error: undefined symbol: __stack_chk_guard
>>> referenced by initramfs.c:444 (/root/scripts/evo/kernel/sony/sagami/init/initramfs.c:444)
>>>               vmlinux.o:(unpack_to_rootfs)
>>> referenced by slab.h:561 (/root/scripts/evo/kernel/sony/sagami/include/linux/slab.h:561)
>>>               vmlinux.o:(unpack_to_rootfs)
>>> referenced by initramfs.c:0 (/root/scripts/evo/kernel/sony/sagami/init/initramfs.c:0)
>>>               vmlinux.o:(unpack_to_rootfs)
>>> referenced 54879 more times
make[1]: *** [/root/scripts/evo/kernel/sony/sagami/Makefile:1200: vmlinux] Error 1
make[1]: Leaving directory '/root/scripts/evo/out/target/product/pdx215/obj/KERNEL_OBJ'
make: *** [Makefile:183: sub-make] Error 2
make: Leaving directory '/root/scripts/evo/kernel/sony/sagami'
15:47:06 ninja failed with: exit status 1
ninja: build stopped: subcommand failed.

**Comment by saku-bruh** [comment]
Could you check if you have `kernel-build-tools` in the `prebuilts` folder?
If not, run:
`git clone https://android.googlesource.com/kernel/prebuilts/build-tools prebuilts/kernel-build-tools && cd prebuilts/kernel-build-tools && git checkout android-13.0.0_r0.65 && cd ../..`
And try to build again.

**Comment by saku-bruh** [comment]
You need to apply this patch to the source for it to build with LLVM.
https://review.lineageos.org/c/LineageOS/android_vendor_lineage/+/344243
